.TH fgen "21st November 2019" "1.2" "fgen man page"
.SH NAME
	fgen - font generator, generate a UTF-8 font of your choice!
.SH SYNOPSIS
	fgen, a UTF-8 font generator. Generate a UTF-8 font of your choice!
.SH OPTIONS
.SH
	--help
		Show a help
.SH
	--blink
		Blink the output
.SH
	--colour
		Choose a random colour for your text

.SH USEFUL KEYS TO USE THE PROGRAM

.SH backspace
	delete the character before the cursor
.SH ctrl + w
	go up from the cursor
.SH ctrl + s
	go down from the cursor
.SH ctrl + a
	go to the left from the cursor
.SH ctrl + d
	go to the right from the cursor
.SH ctrl + space
	delete the character under the cursor
.SH ctrl + r
	clear the input
.SH ctrl + l
	clear the input
.SH ctrl + k
	exit prompt
.SH ctrl + c
	exit prompt

.SH SUGGESTION:
	Suggestion: This program uses UTF-8 fonts, and can be copied to use them on the web (if supported).

.SH AUTHOR
	Sourav Goswami

.SH BUG REPORT AND CONTACT DEVELOPER
	souravgoswami@protonmail.com
